### ISSUE TITLE
MySQL в базовом проекте и первое ДЗ

### ISSUE THREAD

**Issue by chrn-feip** [praisethedeviI/fefu-backend-3-6#2]
1. Обновите базовый репозиторий таким образом, чтобы в нём уже был pgsql. Лучше всего это сделать заново. Или можно попробовать удалить локальный .env и пересобрать контейнеры. Потому что есть вероятность, что .env у вас сейчас неправильным, в нём нет переменных окружения для PostgreSQL.
2. В коде первого ДЗ оставьте только правки, касающиеся PgAdmin.

**Comment by praisethedeviI** [comment]
Обновил базовый проект, добавил pgsql.
